CREATE DATABASE IF NOT EXISTS bank_db;
USE bank_db;

CREATE TABLE IF NOT EXISTS UTILISATEURS (
  id_utilisateur INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(50) NOT NULL,
  prenom VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  mot_de_passe VARCHAR(255) NOT NULL,
  telephone VARCHAR(20),
  adresse VARCHAR(255),
  role VARCHAR(20) DEFAULT 'client',
  statut VARCHAR(20) DEFAULT 'actif',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS COMPTES (
  id_compte INT AUTO_INCREMENT PRIMARY KEY,
  numero_compte VARCHAR(20) NOT NULL UNIQUE,
  type_compte VARCHAR(20) NOT NULL DEFAULT 'courant',
  solde DECIMAL(15, 2) DEFAULT 0.00,
  statut VARCHAR(20) DEFAULT 'actif',
  id_utilisateur INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_utilisateur) REFERENCES UTILISATEURS(id_utilisateur) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
  id_transaction INT AUTO_INCREMENT PRIMARY KEY,
  type_transaction VARCHAR(20) NOT NULL,
  montant DECIMAL(15, 2) NOT NULL,
  date_transaction TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  description VARCHAR(255),
  statut VARCHAR(20) DEFAULT 'valide',
  compte_source_id INT,
  compte_destination_id INT,
  FOREIGN KEY (compte_source_id) REFERENCES COMPTES(id_compte) ON DELETE SET NULL,
  FOREIGN KEY (compte_destination_id) REFERENCES COMPTES(id_compte) ON DELETE SET NULL
);
